workflow:
    - deploy

shared:
    image: python:2

jobs:
  main:
    steps:
      - init: pip install -r requirements.txt
      - validate: markdownlint docs/
      - build: mkdocs build

  deploy:
      steps:
          - setup-ci: git clone https://gist.github.com/3d2388b2a7ba658cdcdaffa8cd874e50.git ci
          - init: pip install -r requirements.txt
          - deploy: ./deploy.sh
      secrets:
          # Pushing tags to Git
          - GIT_KEY
