shared:
  image: jekyll/builder:4

jobs:
  main:
    requires: [~pr, ~commit]
    steps:
        - build: jekyll build --source docs --destination _site
        - proof: /usr/gem/bin/htmlproofer --assume-extension --allow-hash-href --empty-alt-ignore --file-ignore '/\/ja\//' --url-ignore '/bitbucket/,/gitlab/,/api\.screwdriver\.cd/' --http-status-ignore 429 _site

  publish:
      requires: [main]
      environment:
          DOCKER_REPO: screwdrivercd/guide
          RELEASE_FILE: guide.tgz
      secrets:
          - DOCKER_TRIGGER
          - GIT_KEY
          - GITHUB_TOKEN
      steps:
          - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
          - build: jekyll build --source docs --destination _site
          - package: tar -C _site -cvzf $RELEASE_FILE .
          - tag: ./ci/git-tag.sh
          - publish: ./ci/git-release.sh
          - docker: |
              ./ci/git-latest.sh
              export DOCKER_TAG=`cat VERSION`
              ./ci/docker-trigger.sh

  deploy:
      requires: [publish]
      environment:
          DOCKER_REPO: screwdrivercd/guide
          K8S_CONTAINER: guide
          K8S_IMAGE: screwdrivercd/guide
          K8S_HOST: kubernetes.default.svc
          K8S_DEPLOYMENT: sdguide
      secrets:
          - K8S_TOKEN
      steps:
          - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
          - get-tag: ./ci/git-latest.sh
          - wait-docker: DOCKER_TAG=`cat VERSION` ./ci/docker-wait.sh
          - deploy-k8s: K8S_TAG=`cat VERSION` ./ci/k8s-deploy.sh
